spring:
  datasource:
    url: jdbc:mysql://{mysql.host}:3306/im?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "******"
logging:
  level:
    com.wish: DEBUG