spring:
  datasource:
    url: jdbc:mysql://172.16.8.13:3306/im?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Cyb20@20
logging:
  level:
    com.wish: DEBUG